apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app  
  namespace: hello-world-app 
spec:
  project: default
  source:
    repoURL: 'https://github.com/sucethra/helo-world-app'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
